### ISSUE TITLE
Custom lyrics doesn't show up on Revanced

### ISSUE THREAD

**Issue by Syber-man** [Natoune/SpotifyMobileLyricsAPI#94]
Device: CMF phone 1, Android 15
Spotify version used for patching with issues: 9.0.56.591
Patched with: Revanced (Patches version: 5.30.0)

ISSUE: Spotify doesn't show lyrics at all even when _change lyrics provider patch is applied_ with IP: lyrics.natanchiodi.fr

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/bb295e00-8a60-4343-b1b7-f4af9a1e88d1" />

**Comment by Natoune** [comment]
Hello,

The server `lyrics.natanchiodi.fr` is currently down.
I'm investigating how to fix a major server issue, likely caused by a change in Spotify API.

Once I've resolved the issue, I'll restart the server and let you know!

**Comment by eljohnzc** [comment]
lyrics still not showing sir i did the custom server and lyrics.natanchiodi.fr but not working

**Comment by mycreation1** [comment]
Not working and yes I also tried making my own lyric server

**Comment by Inferno1122** [comment]
Tried with both cloudflare workers and vercel. Both return errors and lyrics don't work

**Comment by Natoune** [comment]
Okay, I'm sorry for this problem.
I just pushed an update that should resolve the issue.

**Comment by LironFridman** [comment]
Awesome man, thank you for all your work :)

**Comment by mananvernekar07** [comment]
> Okay, I'm sorry for this problem. I just pushed an update that should resolve the issue.

Naah, I just repatched using custom lyrics provider but it still dont show lyrics🥲

**Comment by jf-617hu8** [comment]
I'm grateful for all the good work that has gone into this project. But, I really really miss how things were before the latest changes. When I deploy my server thru Vercel, using Neon as DB, I end up getting the lyrics from LRCLIB rather than getting the lyrics from just one source (Musixmatch). I prefer to get all the lyrics from Musixmatch, just like before because they run much smoother without much delay and because the lyrics are more accurate and look better. 

However, when the lyrics from Musixmatch are fetched for one song, when that exact same song is played once again, I see a black screen instead of its lyrics, as shown down below.


[When playing a song for the first time](https://imgur.com/a/67PTVvE)

[When playing the exact same song again](https://imgur.com/a/cEJijYk)

**Comment by Inferno1122** [comment]
> I'm grateful for all the good work that has gone into this project. But, I really really miss how things were before the latest changes. When I deploy my server thru Vercel, using Neon as DB, I end up getting the lyrics from LRCLIB rather than getting the lyrics from just one source (Musixmatch). I prefer to get all the lyrics from Musixmatch, just like before because they run much smoother without much delay and because the lyrics are more accurate and look better.
> 
> However, when the lyrics from Musixmatch are fetched for one song, when that exact same song is played once again, I see a black screen instead of its lyrics, as shown down below.
> 
> [When playing a song for the first time](https://imgur.com/a/67PTVvE)
> 
> [When playing the exact same song again](https://imgur.com/a/cEJijYk)

Im also encountering the black screen issue when playing the same song again. Hosting on vercel with neon DB. Though I think LRCLIB integration would be a good thing as a fallback because musixmatch on spotify doesn’t provide lyrics for a ton of songs.

**Comment by jf-617hu8** [comment]
@Inferno1122 I just changed the SP_DC value to see if this fixes the black screen issue. Also tried to purge the cache on both ends (the app on my phone and the server on Vercel) as well as reinstalling the app on the phone. But, the problem with the black screen still persists. As for Musixmatch vs. LRCLIB, I agree that having the ability to fall back to another source is needed for those songs which don't have their own lyrics. The problem, however, is that many mainstream songs which originally have Musixmatch lyrics attached to themselves have all of a sudden switched source to LRCLIB instead of Musixmatch, which is itself a disappointment in terms of UX. This wasn't the case before.

**Comment by mycreation1** [comment]
Do we have any update on the lyric not showing in spotify revanced I just tried patching with my own vercel server and it didn't show any lyrics for any songs

**Comment by legouju** [comment]
Was able to self host fine on docker (reverse proxy with caddy/cloudflare dns domain).

Spotify: 9.0.58.596
Revance Patch: 5.30.0

Thank you [Natoune](https://github.com/Natoune)!!!

**Comment by mananvernekar07** [comment]
Thankyou Dev!!
I tried again the clone deployment of your project and this time it worked...
just copy domain by long pressing after setting up project server and db
Copy Link text
Paste in lyrics provider and Patch!!

<img width="487" height="161" alt="Image" src="https://github.com/user-attachments/assets/49e2786a-0ba8-401e-ab3d-8eb967ce65f9" />

**Comment by mananvernekar07** [comment]
> Thankyou Dev!! I tried again the clone deployment of your project and this time it worked... just copy domain by long pressing after setting up project server and db Copy Link text Paste in lyrics provider and Patch!!
> 
> <img alt="Image" width="487" height="161" src="https://private-user-images.githubusercontent.com/118718800/464605796-49e2786a-0ba8-401e-ab3d-8eb967ce65f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxMzg1MTQsIm5iZiI6MTc1MjEzODIxNCwicGF0aCI6Ii8xMTg3MTg4MDAvNDY0NjA1Nzk2LTQ5ZTI3ODZhLTBiYTgtNDAxZS1hYjNkLThlYjk2N2NlNjVmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcxMFQwOTAzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTNjMTA2ZmEyYmU5MmFlOGY0ZWZhZDQwODQ5Yzg3ZWEyZTA4ZTAwYzQwMWEyN2JjMDczOTg0MWY5MjI5MWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w_mwmWPaWP7BO5QFsIcI5BQE7quJRi8m680zZIf4Xog">

But when I reopened the app 
The login issue for different region is coming
for Facebook login on Spotify
It works but now this new issue arrived

**Comment by mycreation1** [comment]
Bruh it still doesn't work for me

> > Thankyou Dev!! I tried again the clone deployment of your project and this time it worked... just copy domain by long pressing after setting up project server and db Copy Link text Paste in lyrics provider and Patch!!
> > <img alt="Image" width="487" height="161" src="https://private-user-images.githubusercontent.com/118718800/464605796-49e2786a-0ba8-401e-ab3d-8eb967ce65f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxMzg1MTQsIm5iZiI6MTc1MjEzODIxNCwicGF0aCI6Ii8xMTg3MTg4MDAvNDY0NjA1Nzk2LTQ5ZTI3ODZhLTBiYTgtNDAxZS1hYjNkLThlYjk2N2NlNjVmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcxMFQwOTAzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTNjMTA2ZmEyYmU5MmFlOGY0ZWZhZDQwODQ5Yzg3ZWEyZTA4ZTAwYzQwMWEyN2JjMDczOTg0MWY5MjI5MWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w_mwmWPaWP7BO5QFsIcI5BQE7quJRi8m680zZIf4Xog">
> 
> But when I reopened the app The login issue for different region is coming for Facebook login on Spotify It works but now this new issue arrived

**Comment by jf-617hu8** [comment]
This is the exact same problem I'm facing too. I'm hosting the lyrics on Vercel along with Neon DB.

[bug(Spotify - Change lyrics provider): Lyrics are dissapearing when you played a track once #5417](https://github.com/ReVanced/revanced-patches/issues/5417#issue-3223976411)

**Comment by mycreation1** [comment]
bro are you going to fix it or ignore or cries for help???

**Comment by LironFridman** [comment]
> bro are you going to fix it or ignore or cries for help???

This guy is giving away his time and expertise for free to the community.
Entitled pricks like you have no place to demand him to work for free at your whim so you can piss right off with that attitude.
Contribute to a fix or shut up(although I'm sure you're not even a programmer and just here to leech off of others work).

**Comment by mycreation1** [comment]
> > bro are you going to fix it or ignore or cries for help???
> 
> This guy is giving away his time and expertise for free to the community. Entitled pricks like you have no place to demand him to work for free at your whim so you can piss right off with that attitude. Contribute to a fix or shut up(although I'm sure you're not even a programmer and just here to leech off of others work).

bruh chill im just asking a question??

**Comment by LironFridman** [comment]
> > > bro are you going to fix it or ignore or cries for help???
> > 
> > 
> > This guy is giving away his time and expertise for free to the community. Entitled pricks like you have no place to demand him to work for free at your whim so you can piss right off with that attitude. Contribute to a fix or shut up(although I'm sure you're not even a programmer and just here to leech off of others work).
> 
> bruh chill im just asking a question??

No you're practically demanding him to fix it right now for you.
Your "question" does not contribute anything to the discussion, which is the point of issues in this website.

**Comment by mycreation1** [comment]
> > > > bro are you going to fix it or ignore or cries for help???
> > > 
> > > 
> > > This guy is giving away his time and expertise for free to the community. Entitled pricks like you have no place to demand him to work for free at your whim so you can piss right off with that attitude. Contribute to a fix or shut up(although I'm sure you're not even a programmer and just here to leech off of others work).
> > 
> > 
> > bruh chill im just asking a question??
> 
> No you're practically demanding him to fix it right now for you. Your "question" does not contribute anything to the discussion, which is the point of issues in this website.

its been 4 days since the creater of this repo talked and I was just wondering when or at all if he was going to fix the issues, and yes I can admit the tone I phrased it was quite bratty, and im sorry for that.

**Comment by LironFridman** [comment]
That's ok, you're probably new to the whole idea of open source projects.
Just please keep in mind that most of the projects you see here are being worked on and maintained by volunteers on their own free time.
Many have jobs and lives and are thus left with limited time on the weekends and such to fix issues raised by the community.
Sorry if I've been too harsh myself, I work on personal and community projects on my own time as well so this is a personal pain point.

**Comment by Natoune** [comment]
Sorry for the late reply, but I'm currently on vacation and I can't work on this project right now.
Also, it's quite difficult to debug all this and know if the issues are caused by the server or by the ReVanced patch.
I'll let you know when I'm working on this project again. In the meantime, feel free to reuse or modify this code if you can to try to resolve any issues.
